# These are supported funding model platforms
# If you want to donate through another method please contact me!

bitcoin: bc1qqyrx74ws33w2wuumw0fdzvejgu6xlkd5tyrtx9
ethereum: 0x4f10C214F271d969E7ff69CE73783A77dD762e2f
